name:                funEvalExpr
version:             0.1.0.0
github:              "MatiCG/EvalExpr"
license:             MIT
author:              "MatiCG"
maintainer:          "MatiCG"
copyright:           "2019 MatiCG"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MatiCG/EvalExpr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib

executables:
  funEvalExpr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funEvalExpr

tests:
  funEvalExpr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funEvalExpr
