name: Haskell CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.2'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      run: make
    - name: Run tests
      run: make run-tests
    - name: Generate coverage report
      uses: 8c6794b6/hpc-codecov-action@v2
      with:
        target: stack:funEvalExpr-test
        excludes: Main,Paths_my_package
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
